spring:
  datasource:
#    mysql:
#      url: jdbc:mysql://localhost:3306/excel_test?useSSL=false&useUnicode=true&characterEncoding=utf-8
#      username: panyi
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
    postgresql:
      url: jdbc:postgresql://localhost:5432/excel_test
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8